### ISSUE TITLE
MailChimp and SettingsPage class

### ISSUE THREAD

**Issue by jonathanbardo** [locomotivemtl/wordpress-chimplet#1]
Since our plugin leverage MailChimp at it's core, I really think we should separate the instance creation of the MailChimp class from the [SettingsPage class](https://github.com/locomotivemtl/wordpress-chimplet/blob/develop/src/Chimplet/SettingsPage.php#L80).

That way the settings page really only deals with settings and we can reuse the MailChimp instance everywhere we need to.

What do you think @mcaskill?

**Comment by mcaskill** [comment]
Definitely!

Should the `\Chimplet\Application` class handle the `\Mailchimp` instance and custom methods or should we have a separate facade for MailChimp like I did for WordPress?

Is the WP facade overkill?

On a similar topic, should/can we modify the `\Singleton` trait (or drop it) to pass a "master" context to the child classes? For example:

In `Application::initialize()`:

```
$this->overview = OverviewPage::get_singleton( $this );
```

Then, in `AdminPage::__construct()`:

```
public function __construct( Application $master = null ) {
    $this->master = $master;

    // Shortcuts
    $this->mc = & $this->master->mc;
    $this->wp = & $this->master->wp;

    if ( ! $this->wp->is_admin() ) {
        return;
    }

    // [...]
}
```

**Comment by jonathanbardo** [comment]
I like the idea of a facade for MailChimp to handle our needs (the WordPress one might be overkill a little bit but I really like the fact that we know right away where the function is coming from. Let's keep it that way!).

I also like the dependency injection singleton pattern you showed. I think it's a good idea in the context we are playing with (`$app` might be a better name than `$master` though). The other option we have is to create 2 protected variables containing the 2 facade in the `Base` class. Dependency injection seems cleaner to me because our admin pages really only lives inside the context of our plugin anyway.

**Comment by jonathanbardo** [comment]
@mcaskill I've been thinking a little and since we are going to use the dependency injection pattern we should get rid of the singleton pattern for all settings pages as it would make a little more sense.
