### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by jonathanbardo** [locomotivemtl/wordpress-chimplet#4]
@mcaskill 
Most WordPress plugins on WordPress.org have banners and I thought it would be cool to give this plugin come colors.

This is my personal contribution to this open source plugin. Let's get this conversation started!

Note: This might need the locomotive logo but I couldn't find it quickly.

Please disregard this completely if you guys have a better idea! I won't be offended at all! I'm no designer :wink:

![chimplet](https://cloud.githubusercontent.com/assets/1933681/6205400/0a627ce0-b53b-11e4-801e-e037c7d8a1eb.png)

**Comment by mcaskill** [comment]
How about using the bananas to mimic a syncing icon.

![v2](https://cloud.githubusercontent.com/assets/29353/6230574/cfeeeb16-b68e-11e4-9eb5-1c4480450ddf.png)

**Comment by mcaskill** [comment]
Maybe with a more abstract pictogram of the banana:

![bananas](http://sensibleworld.com/wp-content/uploads/034-Bananas.png)

— http://sensibleworld.com/news/034-bananas-icon/

**Comment by jonathanbardo** [comment]
I think the "flatter" banana icon is better! Not sure about the orange though...
