### ISSUE TITLE
User Roles in MailChimp: List Fields v. List Groups

### ISSUE THREAD

**Issue by mcaskill** [locomotivemtl/wordpress-chimplet#5]
The _User Role_, as a Grouping, is more of a _radiobox_-type of option; you can only ever belong to one in WordPress and thus should be the same in MailChimp (as opposed to taxonomies that are checkbox-style).

I'm wondering if we couldn't take advantage of List Fields (_|MERGE|_ tags) for something like the User Roles. Make it a hidden field and we'd be saving some group slots for actual group-like items like taxonomies.

/to @jonathanbardo

**Comment by jonathanbardo** [comment]
So actually in WordPress a user can have multiple roles (some plugins allows you to do that and WordPress supports it but it's not implemented in the default UI). 

Can you explain your idea for merge tags a little further. I'm not sure I follow you there.

**Comment by jonathanbardo** [comment]
So actually in WordPress a user can have multiple roles (some plugins allows you to do that and WordPress supports it but it's not implemented in the default UI). See https://wordpress.org/plugins/user-role-editor/ for example.

Can you explain your idea for merge tags a little further. I'm not sure I follow you there.

**Comment by mcaskill** [comment]
Instead of syncing selected _WordPress User Roles_ to _List Groups_, they would be synced to a _List Field_.

![mailchimp-list-fields](https://cloud.githubusercontent.com/assets/29353/6235011/21ba2172-b6ad-11e4-9d51-4764904c8daa.png)

Although:

> Lists are limited to a maximum of 30 data fields for each subscriber. If you want more than 30 fields of information about your subscribers, use groups to help consolidate list fields.

— [Source](http://kb.mailchimp.com/lists/managing-subscribers/manage-list-and-signup-form-fields)

**Comment by mcaskill** [comment]
Hrm. The _multiple roles_ feature from User Role Editor is an interesting conundrum, in which case List Groups _as checkboxes_ is the better alternative.

**Comment by jonathanbardo** [comment]
Alright, that seems okay with me. Let's sync the role with the user fields and not with groups. I'll remove this portion of code tonight and dig into user syncing right away.

**Comment by jonathanbardo** [comment]
So basically we will create a new merge tag using the [API](https://apidocs.mailchimp.com/api/2.0/lists/merge-vars.php) if the merge tab doesn't already exist. It will be a dropdown and it will not be visible. 

Once the user has selected at least one role, we will present him with a syncing button to do the initial sync. Once the sync is done, the system will sync every new user with the specified role to MailChimp. Of course, if a user change role, we will also check if he needs to be sent to MailChimp. 

@mcaskill do we lock the user role once the initial sync is done? I'm thinking if an admin decide he wants to sync a new role he will need to do the syncing again. Also, do we take into account that a role might be removed? To we go and delete all user from MailChimp with that role if that happens?
