### ISSUE TITLE
Is the current usage of esc_html__() excessive?

### ISSUE THREAD

**Issue by mcaskill** [locomotivemtl/wordpress-chimplet#7]
Every single hardcoded, translatable, string is being wrapped by `esc_html_*()`. Is this from PHPCS-WP?

I'm forced to abstract a lot of the strings to include small tags like `<em>` in text. Could we limit the need down to `esc_html()`for dynamic values and leave hardcoded translatable strings alone?

**Comment by jonathanbardo** [comment]
I've been through a lot of discussion about this with collegues in the past and we basically establish that to prevent any kinds of security holes we should always escape html from translatable text field.

Also (for example) WordPress VIP has intensive code sniffer for everything that gets outputed to the browser (sanitize everything coming in and escape everything going out to prevent any king of CSRF).

To include html tags one can also do something like (in template):

``` php
printf( esc_html__( 'Some random string with %s bold %s', 'domain' ), '<strong>', '</strong>' );
```
